import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { Intro } from "@/components/intro";
import { cn } from "@/lib/utils";

const eUkraine = localFont({
  src: "../../../public/e-UkraineHead-Regular.otf",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("flex min-h-screen flex-col", eUkraine.className)}>
        <Intro />

        <Navbar />
        {children}
      </body>
    </html>
  );
}
